

spring:
  spring:
    config:
      activate:
        on-profile: dev
  server:
    port: 8080

  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/testdb?allowPublicKeyRetrieval=false&useSSL=false
    username: root
    password: 
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: 'create-drop'

fileRepositoryFolder: D:\\Desktop\\file repository\\

---
spring:
  config:
    activate:
      on-profile: test
  server:
    port: 3000

  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/cpbt
    username:
    password:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: 'create-drop'

---
spring:
  config:
    activate:
      on-profile: prodaction

  server:
    port: 8080

  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/cpb
    username:
    password:
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: 'update'