

spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/cpb
    username:
    password: 
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: 'create-drop'